# Generated by Django 2.2.4 on 2020-04-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadphoneHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_model', models.CharField(max_length=100)),
                ('hh_serial', models.CharField(max_length=100)),
                ('hh_pDate', models.DateField(null=True)),
                ('hh_pDetail', models.TextField(null=True)),
                ('hh_rDate', models.DateField(null=True)),
                ('hh_rDetail', models.TextField(null=True)),
                ('hh_receiver', models.CharField(max_length=100, null=True)),
                ('hh_checker', models.CharField(max_length=100, null=True)),
                ('hh_state', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
