# Generated by Django 2.2.4 on 2020-04-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_checker',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_pDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_pDetail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_rDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_rDetail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_receiver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
