# Generated by Django 2.2.4 on 2020-05-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200414_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_model', models.CharField(max_length=100)),
                ('h_serial', models.CharField(max_length=100)),
                ('h_pDate', models.DateField(null=True)),
                ('h_pDetail', models.TextField(null=True)),
                ('h_rDate', models.DateField(null=True)),
                ('h_rDetail', models.TextField(null=True)),
                ('h_receiver', models.CharField(max_length=100, null=True)),
                ('h_checker', models.CharField(max_length=100, null=True)),
                ('h_state', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_state',
            field=models.CharField(max_length=100),
        ),
    ]
