# Generated by Django 2.2.4 on 2020-05-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200507_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_checker',
            field=models.CharField(max_length=100, null=True, verbose_name='확인자'),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_model',
            field=models.CharField(max_length=100, verbose_name='모델명'),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_pDate',
            field=models.DateField(null=True, verbose_name='지급일'),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_pDetail',
            field=models.TextField(null=True, verbose_name='지급내용'),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_rDate',
            field=models.DateField(null=True, verbose_name='반납일'),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_rDetail',
            field=models.TextField(null=True, verbose_name='반납내용'),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_receiver',
            field=models.CharField(max_length=100, null=True, verbose_name='인수자'),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_serial',
            field=models.CharField(max_length=100, verbose_name='일련번호'),
        ),
        migrations.AlterField(
            model_name='headphonemain',
            name='hp_state',
            field=models.CharField(max_length=100, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='history',
            name='h_checker',
            field=models.CharField(max_length=100, null=True, verbose_name='확인자'),
        ),
        migrations.AlterField(
            model_name='history',
            name='h_model',
            field=models.CharField(max_length=100, verbose_name='모델명'),
        ),
        migrations.AlterField(
            model_name='history',
            name='h_pDate',
            field=models.DateField(null=True, verbose_name='지급일'),
        ),
        migrations.AlterField(
            model_name='history',
            name='h_pDetail',
            field=models.TextField(null=True, verbose_name='지급내용'),
        ),
        migrations.AlterField(
            model_name='history',
            name='h_rDate',
            field=models.DateField(null=True, verbose_name='반납일'),
        ),
        migrations.AlterField(
            model_name='history',
            name='h_rDetail',
            field=models.TextField(null=True, verbose_name='반납내용'),
        ),
        migrations.AlterField(
            model_name='history',
            name='h_receiver',
            field=models.CharField(max_length=100, null=True, verbose_name='인수자'),
        ),
        migrations.AlterField(
            model_name='history',
            name='h_serial',
            field=models.CharField(max_length=100, verbose_name='일련번호'),
        ),
        migrations.AlterField(
            model_name='history',
            name='h_state',
            field=models.CharField(max_length=100, verbose_name='상태'),
        ),
    ]
